# Generated by Django 4.2.5 on 2023-11-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcarespecialty',
            name='patient',
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='dietary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='smoking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient'),
        ),
    ]
