# Generated by Django 4.2.5 on 2023-11-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
