# Generated by Django 4.2.5 on 2023-11-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('duration_on_dialysis', models.CharField(max_length=50)),
                ('current_medication', models.TextField()),
                ('general_status', models.CharField(max_length=50)),
                ('access_site_status', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=20)),
                ('qb_rate', models.CharField(max_length=20)),
                ('ultrafiltration_volume', models.CharField(max_length=20)),
                ('investigations', models.TextField()),
                ('plan', models.TextField()),
                ('additional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='patientapp.additionaluser')),
            ],
        ),
    ]
