# Generated by Django 4.2.5 on 2023-09-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialization',
            old_name='specialized_category',
            new_name='doctor_category',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
