# Generated by Django 4.2.5 on 2023-11-19 01:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('heart_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('blood_pressure_systolic', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_diastolic', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)])),
                ('respiratory_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(40)])),
                ('oxygen_saturation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
    ]
