# Generated by Django 4.2.5 on 2023-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_additionaluser_age_additionaluser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
