# Generated by Django 4.2.5 on 2023-09-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='age_years',
        ),
    ]
