# Generated by Django 4.2.5 on 2023-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_remove_medicalhistoryy_age_medicalhistoryy_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
