# Generated by Django 4.2.5 on 2023-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0011_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
