# Generated by Django 4.2.5 on 2023-10-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0013_prescriptionstatus_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investgation',
            new_name='Investigation',
        ),
        migrations.RenameField(
            model_name='medical_history',
            old_name='investgation',
            new_name='investigation',
        ),
    ]
