# Generated by Django 4.2.5 on 2023-10-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0016_remove_medicalhistoryy_current_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionstatus',
            name='newprescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.prescription'),
        ),
    ]
