# Generated by Django 4.2.5 on 2023-10-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0018_consultation_diagnosis_price_examination_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='Consultation_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medical_history',
            old_name='consultations',
            new_name='consultation',
        ),
    ]
