# Generated by Django 4.2.5 on 2023-10-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0019_rename_consultation_type_consultation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_collection', models.DateTimeField()),
                ('ordering_physician', models.CharField(max_length=100)),
                ('specimen_type', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('normal_range', models.CharField(max_length=50)),
                ('test_code', models.CharField(max_length=20, unique=True)),
                ('methodology', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.FloatField()),
                ('units', models.CharField(max_length=20)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('reference_range', models.CharField(max_length=50)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.labreport')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.labtest')),
            ],
        ),
    ]
