# Generated by Django 4.2.5 on 2023-10-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0020_labreport_labtest_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('labtest', 'Lab Test'), ('labreport', 'Lab Report'), ('testresult', 'Test Result')], max_length=10)),
                ('date_of_collection', models.DateTimeField()),
                ('ordering_physician', models.CharField(max_length=100)),
                ('specimen_type', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=50, null=True)),
                ('test_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('reference_range', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='lab_report',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='lab_test',
        ),
        migrations.DeleteModel(
            name='LabReport',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
