# Generated by Django 4.2.5 on 2023-10-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0021_labdata_remove_testresult_lab_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_unit', models.CharField(max_length=20)),
                ('normal_range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('specimen_type', models.CharField(max_length=50)),
                ('collection_date_time', models.DateTimeField()),
                ('lab_name', models.CharField(max_length=100)),
                ('report_number', models.CharField(max_length=20)),
                ('report_generated_date_time', models.DateTimeField()),
                ('signature', models.CharField(max_length=100)),
                ('credentials', models.CharField(max_length=100)),
                ('additional_notes', models.TextField()),
                ('barcode', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='LabData',
        ),
    ]
