# Generated by Django 4.2.5 on 2024-01-25 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0022_labreport_delete_labdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistoryy',
            name='patientAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
